
export const VUE_APP_SUPABASE_URL = 'https://vhxoddxbxnxexzvxffbh.supabase.co'
export const VUE_APP_SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoeG9kZHhieG54ZXh6dnhmZmJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTExNjY5NDgsImV4cCI6MjAwNjc0Mjk0OH0.MbJg0sOJAInRDmLNX4e1ZQHWfBFbIYv3A6n4FQlOos8'